[package]
name = "ink_storage"

edition.workspace = true
categories.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

authors = ["Parity Technologies <admin@parity.io>", "Robin Freyler <robin@parity.io>"]
description = "[ink!] Data structures to organize and manipulate ink! contract storage."
documentation = "https://docs.rs/ink_storage/"
include = ["Cargo.toml", "src/**/*.rs", "README.md", "LICENSE"]
readme = "README.md"

[dependencies]
ink_env = { version = "4.2.0", path = "../env/", default-features = false }
ink_metadata = { version = "4.2.0", path = "../metadata/", default-features = false, features = ["derive"], optional = true }
ink_primitives = { version = "4.2.0", path = "../primitives/", default-features = false }
ink_storage_traits = { version = "4.2.0", path = "traits", default-features = false }
ink_prelude = { version = "4.2.0", path = "../prelude/", default-features = false }

scale = { package = "parity-scale-codec", version = "3.4", default-features = false, features = ["derive"] }
derive_more = { version = "0.99", default-features = false, features = ["from", "display"] }
scale-info = { version = "2.6", default-features = false, features = ["derive"], optional = true }
cfg-if = "1.0"
array-init = { version = "2.0", default-features = false }

[dev-dependencies]
quickcheck = "1.0"
quickcheck_macros = "1.0"
itertools = "0.11"

ink = { path = "../ink" }

[features]
default = ["std"]
std = [
    "ink_metadata/std",
    "ink_env/std",
    "ink_prelude/std",
    "ink_primitives/std",
    "ink_storage_traits/std",
    "scale/std",
    "scale-info/std",
]
ink-fuzz-tests = ["std"]
